- name: Install nginx
  become: yes
  apt:
    name: nginx
    state: latest

- name: Copy nginx site configuration
  become: yes
  template:
    src: roles/nginx/templates/share.j2
    dest: /etc/nginx/sites-available/share

- name: Disable default site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Enable share site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/share
    state: link
    src: /etc/nginx/sites-available/share
  notify: Restart nginx
