- name: Golb setup
  hosts: all
  tasks:
    - name: Update APT sources
      become: yes
      apt:
        update_cache: yes

    - name: Create share directory
      become: yes
      file:
        path: "{{ share_dir }}"
        state: directory
        mode: a+rwx

    - import_role:
        name: samba

    - import_role:
        name: nginx

    - import_role:
        name: motd
