- name: Install Samba and wsdd
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - samba
    - wsdd

- name: Copy Samba configuration file
  become: yes
  template:
    src: roles/samba/templates/smb.conf.j2
    dest: /etc/samba/smb.conf

- name: "Create Samba user {{ samba_user }}"
  become: yes
  user:
    name: "{{ samba_user }}"

- name: "Remove SMB password requirement for Samba user {{ samba_user }}"
  become: yes
  command: "smbpasswd -a -n {{ samba_user }}"
  notify: Restart Samba
