- name: Install Samba and wsdd
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - samba
    - wsdd

- name: Copy Samba configuration file
  become: yes
  template:
    src: roles/samba/templates/smb.conf.j2
    dest: /etc/samba/smb.conf

- name: Create user golb
  become: yes
  user:
    name: golb

- name: Remove SMB password requirement for user golb
  become: yes
  command: smbpasswd -a -n golb
  notify: Restart Samba
